Added simple animation functionality and preset hotkey
vwout/obs-visca-control pull request #3
Opened 2021-09-03 21:25 UTC by christinoleo

I needed some added functionality for my usecase and thought of contributing back in case you think it's useful.
Two main changes:
1. I added the presets 1 through 9 as hotkeys. This way, I am able to easily automate this through external macros (Touch Portal in my case)
2. I added the action "Animate" and the settings of animation direction and speed (no zoom because I don't need so I didn't take the time to make it). This way you can pan the camera over a crowd automatically in a scene and if you switch scenes, this animation is canceled. Also is helpful if used in conjunction with external macros (Touch Portal in my case) to switch camera and use timers to position the PTZ camera to the beginning of the animation and switch back to the PTZ camera when it begins the animation.

2021-09-06 21:11 UTC, vwout requested changes
Thank you very much for your additions. This feedback, in contrary to a simple feature request, is highly appreciated.
I do have some remarks, since the implementation is not clean and sometimes probably not fully correct. In case you don't feel like rewriting, I will probably cherry-pick your ideas and integrate them eventually.

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +local previous_actions = {}
I wonder why previous_actions is a table. To my experience, camera's only 'remember' the last parameters set for a certain command (you are only using the 'PanTilt' command); setting a new value will overwrite earlier values. The stop-command for all will for that reason always be 'stop'. Maybe combining PanTilt and Zoom would require two stop commands, but since PanTilt and Zoom can only be active at the same time because of combined use of the scene action (Animate) and a shortcut-key triggered zoom, both actions will also be terminated via their own paths, so no backlog keeping is needed.
There are a few other shortcomings to the implementation that I will address further down.

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +    Preset_1 = 9,
Instead of creating an action for each preset, please use one action 'Preset' and use the preset number as an argument the function `do_cam_action_start`. This reduces the clutter and simplifies the extension to more than 9 presets. In fact, this action already exists; that is `Preset_Recal` (value=2).

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +local function do_cam_action_start(camera_id, camera_action, action_arg, scene_animation_direction, scene_animation_speed)
The arguments `scene_animation_direction` and `scene_animation_speed` are only applicable to one action only. The `action_arg` is generic, although only used for the action `Preset_Recal` so far. In order to support more arguments, ellipses could be used (but it would make the interface complicated, because of the very week interface). I would suggest to change `action_arg` into `action_args` and make it a table, allowing named arguments, so e.g.:
```
do_camera_action_start(1, actions.Preset_Recall, { preset = 1 })
```
or
```
do_camera_action_start(1, actions.Animate, { direction = Visca.PanTilt_directions.up, speed = 2.6 })
```

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +        elseif camera_action == actions.Preset_1 then
As mentioned above, please use `action` `actions.Preset_Recal` with `action_arg`.

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +    log("Stop cam %d @%s action %d (arg %d)", camera_id, camera_address, camera_action or 0, action_arg or 0)
The parameter `camera_action` shall not be null. If it is, that is a programmer error.

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +        { name = "preset_1", descr = "Preset 1", action = actions.Preset_1 },
In order to use `actions.Preset_Recal`, add a `preset` entry to this table.
```suggestion
        { name = "preset_1", descr = "Preset 1", action = actions.Preset_Recal, action_args = { preset = 1 } },
```
The action_args then need to be passed to `cb_camera_hotkey`.

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +    local debug = obs.obs_properties_add_bool(props, "debug", "debug log (needs refresh)")
When you register a callback, it will become effective immediately.
```suggestion
    local debug = obs.obs_properties_add_bool(props, "debug", "debug log (needs refresh)")
    obs.obs_property_set_modified_callback(debug, function (props, property, settings)
      ...
    end)
```

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +                for a,data in pairs(previous_actions) do
When not using `a`, use `_`.
The actual remark to make here however is that you are always stopping all actions present in `previous_actions` whenever a preview is shown. This means that when an animation is still onging for the scene that is on Program, it will always be stopped when a scene with has a Visca control item in it.
If this is needed at all (see my earlier remark about `previous_actions` being a table, it probably needs to be executed only when the involved camera is not on Program, see line 635.

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +                -- table.remove(previous_actions, a)
Besides the fact that the use of a table for `previous_actions` is probably not needed, removal of the executed entry is correct. The check at line 684 however is not the right way; instead, the table should be iterated in reverse at line 681 (rendering line 684 useless), starting with the stop command for the last executed command first. By doing that, you are sure that a later added command is never accidentally stopped. 

Most probably you can get away with checking whether this scene has an action and if so, send the corresponding stop action. If it already stopped, it does no harm. That's a lot easier than global bookkeeping.

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +        if data.source_name == source_name and data.scene_action == actions.Animate then
This is a valid and correct check that is missing in `fe_callback`. The limitation to `actions.Animate` actions only is debatable. For now it's ok, but you can probably leave it out.

2021-09-06 21:11 UTC, vwout commented on obs-visca-control.lua
> +	local source_name = obs.obs_source_get_name(source)
Please mind your indentation (applies to all modifications)

2021-09-09 21:32 UTC, christinoleo commented
I wouldn't mind rewriting but i am completely full of things currently, so I'd take a while before having the time to do them. Feel free to cherry pick ideas and whenever i came I'll see if there is anything left and will focus on that.

2021-09-11 20:20 UTC, vwout commented
Applied and reworked the changes is this pull request in commits 90c508a and 
2350516 .

2021-09-11 20:20 UTC, closed without merging